name: Deploy Reservas EC2 1.6

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Subir archivos por SCP a EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: "."          
        target: "~/reservas" 

    - name: Ejecutar comandos en EC2 vía SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd ~/reservas/microservicios/reservas
          docker build -t reservas .
          docker stop reservas || true
          docker rm reservas || true
          docker run -d --name reservas -p 3030:3030 reservas
